### ISSUE TITLE
Need pypi packaging.

### ISSUE THREAD

**Issue by alinik** [soroush-app/bot-python-sdk#1]
we need to change file structure to create pip format.

`cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git` helps

**Comment by mh-iranpak** [comment]
Hi.
pypi packaging will be created soon.

**Comment by alinik** [comment]
I Open a PR:  [PR-3](https://github.com/soroush-app/bot-python-sdk/pull/3).
I also upload very first version as [soroush-python-sdk](https://pypi.org/project/soroush-python-sdk/).
please give me your pypi user to add use as Maintainer too
