### ISSUE TITLE
عدم دریافت پیام آخر توسط کد

### ISSUE THREAD

**Issue by amin145** [soroush-app/bot-python-sdk#12]
سلام و خدا قوت
کدهای مثال -مثلا کد اکو- را اجرا کردم ولی همواره پیام یکی مانده به آخر را در اجرای کددریافت و در ترمینال مشاهده میکنم. پیام آخر نمایش داده نمیشود ایراد کجاست؟

**Comment by mh-iranpak** [comment]
سلام
متشکر
دقیقا کد مثال رو اجرا می‌کنید؟ در غیر اینصورت لطفا دقیقا تکه کدی رو که اجرا  می‌کنید اینجا بذارید تا بررسی بشه

**Comment by amin145** [comment]
دقیقا کد اکو رو اجرا میکنم

**Comment by amin145** [comment]
با عرض معذرت، خواستم راهنمایی کنین که مشکل از کجاست. ممنون

**Comment by mh-iranpak** [comment]
با عرض پوزش بابت تاخیر
آیا همچنان این مشکل رو دارین؟
میشه برای اطمینان بیشتر، عینا تصویری از تکه کدی که اجرا میکنید و پاسخی که میگیرید رو بفرستید؟

**Comment by amin145** [comment]
بله
مشکل همچنان هست


`
from sys import path
path.append('..')
from client import Client
bot_token = '....BlahBlahBlah_RobotHahstag....Removed by myself'

bot = Client(bot_token)

while 1 :
	try:
		messages = bot.get_messages()
		for message in messages:
			print("New message from {} \nType: {}\nBody: {}".format(message['from'], message['type'], message['body']))
			message['to'] = message['from']
			message.pop('from')
			message.pop('time')

			[error, success] = bot.send_message(message)

			if success:
				print('Message sent successfully')
			else:
				print('Sending message failed: {}' .format(error))

	except Exception as e:
		print(e.args[0])
`
![sorooshbug](https://user-images.githubusercontent.com/34162071/52323850-012d0f00-29f4-11e9-8287-3348f3d7dc9b.jpg)

**Comment by mh-iranpak** [comment]
نسخه ي‌لایبرری تون آخرین لایبرری روی گیتهاب هست؟ یعنی قدیمی نیست لایبرری تون و به روز هست؟

**Comment by amin145** [comment]
بله. مجددا هم امتحان کردم و همه چیز رو آپدیت کردم. با اینحال مشکل هنوز هست.

**Comment by mh-iranpak** [comment]
بله بنده امتحان کردم و مشکلی نیست. همچنین با استفاده از لایبرری چندین بات نوشته شده. لطفا کل پروژه تون رو زیپ کنید و به آدرس ایمیل
mh.iranpak1997@gmail.com
ارسال کنید تا کامل بررسی کنم.

**Comment by amin145** [comment]
فرستادم خدمت تون

**Comment by amin145** [comment]
من الان تحت ویندوز اجرا کردم و مشکلی نبود. 
 روی لینوکس اجراشده روی بوردهای رزپریپای با مشکل بالا مواجه هستم
دلیلی به نظرتون میرسه؟

**Comment by mh-iranpak** [comment]
بله همونطور که گفتم بنظر مشکل از سیستم میزبان هست. امکانش رو دارین روی یک برد رزبری پای دیگه هم امتحان کنید؟

**Comment by amin145** [comment]
بله. روی یک رزپری دیگه امتحان کردم و مشکلی نداشت.
اگر بخوام بصورت دقیق گفته باشم دستگاه اولیه
OrangePi
بود و دستگاهی که الان جواب میده رزپری پای هست
ممکنه ایراد از کجا باشه؟

**Comment by mh-iranpak** [comment]
این مورد باید بطور مفصل بررسی بشه که چه دستگاه هایی و به چه علت با این مشکل مواجه میشن. فعلا چیزی بنظر بنده نمیرسه اما بررسی خواهد شد
