### ISSUE TITLE
 cannot import name 'Client' from 'client'

### ISSUE THREAD

**Issue by C7pH0r** [soroush-app/bot-python-sdk#13]
من کارای اولیه رو انجام دادم:
git clone https://github.com/soroush-app/bot-python-sdk
cd bot-python-sdk
pip install -r requirements.txt

ولی کتاب خونه رو نمیشناسه.چیکار کنم؟

**Comment by iranpak** [comment]
سلام.
یعنی موقع اجرا به مشکل بر میخوره؟ یا صرفا توی محیط کد زنی نمیشناسه؟
به این هم دقت کنید که این کتابخونه فعلا مانند کتابخونه هایی که با
pip
دانلود میکنید نیست و جزو پکیج های پایتون محسوب نمیشه.
برای استفاده از این کتابخونه باید فایل
Client.py
رو کنار کدی که می‌خواین ازش استفاده کنین قرار بدین.

**Comment by C7pH0r** [comment]
ممنون
منبع کاملی وجود داره تا کامل کار با این کتابخانه رو اموزش بده؟

**Comment by iranpak** [comment]
توی پوشه‌ی
examples
تمامی مثال های مورد نیاز وجود داره
و در صورت نیاز به راهنمایی بیشتر میتونید همسنجا سوالاتتون رو بپرسید

**Comment by C7pH0r** [comment]
چطور میشه وقتی کاربر ربات را استارت کنه یک پیغام به طورت خودکار براش ارسال بشه؟

**Comment by iranpak** [comment]
برای مشاهده جزئیات پیام های در یافتی و انواع پیام ها به 
https://soroush-app.ir/developer.html
مراجعه کنید. در این صفحه جزئیات کار با
api
بات سروش توضیح داده شده که این کتابخانه بر اساس اون api 
نوشته شده.
در بخش اوناع تایپ های پیام ها میتونید مشاهده کنید.
