### ISSUE TITLE
nickName و phoneNo

### ISSUE THREAD

**Issue by rahel14** [soroush-app/bot-python-sdk#2]
سلام خسته نباشید
nickName و phoneNo
هنوز فعال نیستند؟ نه میشه ارسال کرد و نه دریافت

**Comment by rahel14** [comment]
با تشکر ویژه از پاسخگوئی
اینجا ارزش ایرانی و خارجی بودن نمایان میشه
ارزش نداره رو همچین برنامه هایی وقت گذاشت

**Comment by mh-iranpak** [comment]
با سلام

خیر. این دو ويژگی اکنون فعال نیستند و در حال توسعه هستند و به زودی به بات اضافه خواهند شد

**Comment by rahel14** [comment]
سلام ضمن تشکر از پاسخگویی
امیدواریم همانگونه که ما از پیام رسان بومی حمایت میکنیم شما هم در پاسخگویی تجدید نظر فرمائید و اینقدر طول نکشد.

**Comment by mh-iranpak** [comment]
حق با شماست
ضمن عذرخواهی از شما و تشکر بابت همراهی‌تان

**Comment by rahel14** [comment]
سلام وقت بخیر
امکانش هست یک زمان تقریبی برای فعال شدنش بفرمائید
چون ما قصد داریم از این طریق احراز هویت کنیم اگر زودتر آماده میشه دیگه برای تاییدش نیاز نداشته باشیم از طریق پیامک و... بفهمیم

**Comment by mh-iranpak** [comment]
سلام
بین دو تا سه ماه دیگه این مورد اضافه خواهد شد. برای اطلاعات بیشتر می‌تونید داخل سروش با آیدی @support در ارتباط باشید.
