### ISSUE TITLE
pass url to send_image

### ISSUE THREAD

**Issue by alirezaimi** [soroush-app/bot-python-sdk#5]
Hi
Why when i'm passing an image url to `send_image` method this error happened :

    >> [Errno 2] No such file or directory: 'http://i66.tinypic.com/xxx.jpg'

I upload my images somewhere else, plz add some option that i can use my url for pictures .

**Comment by mh-iranpak** [comment]
Hi.
for sending an image you should first upload it to **soroush bot servers** by `upload_file` method, then the server will give you it's url in the response. and you should put it in the `send_image` method to send it for server. consider that for upload a file in bot, it should exist on your local machine and give it's local path to the `upload_file` method.
You can see complete  example of sending an image  in [this example](https://github.com/soroush-app/bot-python-sdk/blob/master/examples/send_image.py)

**Comment by alirezaimi** [comment]
thanks, 
I did this way,
bot if I upload my images or some other files somewhere else, is there any option that i can use my url for files ?

**Comment by mh-iranpak** [comment]
No
because as you can see in server response for `upload_file`, the urls are not usual urls and are formatted and special urls
