### ISSUE TITLE
ادد کردن ربات در گروه 

### ISSUE THREAD

**Issue by mojtaban12** [soroush-app/bot-python-sdk#7]
سلام چطوری میشه یک ربات رو عضو یک گروه کرد. با نسخه ویندوزی که اصلا نمی شه گروه ساخت که بشه ادد کرد و با آی او اس هم فقط لیست کاربران قابل مشاهده است برای اضافه کردن به گروه و با شناسه ربات هم نمی شه پیدا کرد!!

**Comment by mh-iranpak** [comment]
سلام.
امکان اضافه کردن بات به کانال و گروه در حال توسعه است و به زودی به بات اضافه خواهد شد. فعلا این امکان در بات وجود ندارد.
