### ISSUE TITLE
text_id or payam_id

### ISSUE THREAD

**Issue by mojtaban12** [soroush-app/bot-python-sdk#8]
سلام 
امکان ریپلی زدن ربات به سوالی که قبلا پرسیده شده وجود داره ؟!
چون فایل های تکستی که ارسال می شن فقط دارای 
from,body,type, time
هستن و معمولا برای ریپلی زدن نیاز به یه چیزی مثل پیام آیدی هم هست!!

**Comment by mh-iranpak** [comment]
سلام.
امکان ریپلای کردن و ارسال آیدی پیام همراه آن به زودی به بات اضافه خواهد شد.
